---
name: test-http-dns-server

update:
  canaries: 2
  canary_watch_time: 1000-60000
  max_in_flight: 5
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- name: test-http-dns-server
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: test-http-dns-server
    release: dns-acceptance

releases:
- name: dns-acceptance
  version: latest

stemcells:
- alias: default
  os: ((base_stemcell))
  version: latest
