---
name: test-recursor

update:
  canaries: 2
  canary_watch_time: 1000-60000
  max_in_flight: 5
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- name: test-recursor
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: test-recursor
    release: dns-acceptance
    properties:
      configurable_response: 1.1.1.1
- name: test-recursor2
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: test-recursor
    release: dns-acceptance
    properties:
      configurable_response: 2.2.2.2

releases:
- name: dns-acceptance
  version: latest

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest
