---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bosh-dns-release
  - name: envs
  - name: bosh-candidate-release

outputs:
  - name: envs
    path: envs-output

params:
  BBL_GCP_SERVICE_ACCOUNT_KEY:
  ENV_NAME:
  BBL_GCP_PROJECT_ID: cf-bosh-core
  BBL_GCP_ZONE: us-central1-a
  BBL_GCP_REGION: us-central1
  BBL_IAAS: gcp

run:
  path: bosh-dns-release/ci/tasks/windows/bbl-up.sh
