---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh-integration
    tag: main

inputs:
  - name: bosh-dns-release
  - name: envs

run:
  path: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.sh

params:
  ENV_NAME: ""
  WINDOWS_OS_VERSION: ""
