---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration
    tag: main

inputs:
  - name: bosh-dns-release
  - name: candidate-release
  - name: version

outputs:
  - name: bumped-version
  - name: final-bosh-dns-release
  - name: final-release-tag

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-dns-release/ci/tasks/finalize-release.sh
