---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration
    tag: main
inputs:
  - name: bosh-dns-release
  - name: bosh-src
  - name: bosh-release

outputs:
  - name: bosh-src
    path: bosh-src-output

run:
  path: bosh-dns-release/ci/tasks/prepare-brats.sh
