---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration
    tag: "main"

inputs:
- name: bosh-dns-release

run:
  path: bosh-dns-release/ci/tasks/test-unit.sh
