---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-bosh-docker
    tag: latest

inputs:
  - name: bosh-dns-release
  - name: candidate-release
  - name: bosh-stemcell
  - name: bosh-candidate-release

params:
  BASE_STEMCELL: ubuntu-bionic

run:
  path: bosh-dns-release/ci/tasks/test-acceptance.sh
