groups:
- name: bosh-dns:docker
  jobs:
  - build-unit-tests-image
  - build-acceptance-tests-windows-image
  - build-acceptance-tests-image

jobs:
- name: build-acceptance-tests-image
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: repo
      trigger: true
    - get: main-bosh-docker-image
      trigger: true
  - put: acceptance-tests-image
    params:
      build: "repo/ci/docker/acceptance-tests"
    get_params:
      skip_download: true
- name: build-acceptance-tests-windows-image
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - put: acceptance-tests-windows-image
    params:
      build: "repo/ci/docker/acceptance-tests-windows"
    get_params:
      skip_download: true
- name: build-unit-tests-image
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - put: unit-tests-image
    params:
      build: "repo/ci/docker/unit-tests"
    get_params:
      skip_download: true

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-dns-release.git
    branch: master
    paths:
    - "ci/docker"
- name: main-bosh-docker-image
  type: registry-image
  source:
    repository: bosh/main-bosh-docker
- name: unit-tests-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: unit-tests
    username: ((docker.username))
    password: ((docker.password))
- name: acceptance-tests-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests
    username: ((docker.username))
    password: ((docker.password))
- name: acceptance-tests-windows-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests-windows
    username: ((docker.username))
    password: ((docker.password))
