---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: bosh-dns-release
  - name: docker-vars
  - name: stemcell

params:
  DEPLOYMENTS_OF_100: 10
  PARALLEL_DEPLOYMENTS: 5
  BBL_STATE_SUBDIRECTORY: test-stress/bbl-state

run:
  path: bosh-dns-release/ci/tasks/test-stress/deploy-n.sh
