---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: bosh-dns-release
  - name: bosh-docker-cpi-release

outputs:
  - name: updated-bbl-state

params:

  BBL_STATE_DIR: test-stress/bbl-state
  BBL_GCP_SERVICE_ACCOUNT_KEY:
  BBL_GCP_PROJECT_ID: cf-bosh-core
  BBL_GCP_ZONE: us-central1-a
  BBL_GCP_REGION: us-central1
  BBL_IAAS: gcp

run:
  path: bosh-dns-release/ci/tasks/test-stress/setup-env.sh
